Pin version of redis gem (#235)
```
  Error: Execution of '/opt/puppetlabs/puppet/bin/gem install --no-rdoc --no-ri redis' returned 1: ERROR:  Error installing redis:
  	redis requires Ruby version >= 2.2.2.
```

As seen in https://github.com/arioch/puppet-redis/pull/230